[project]
name = "pomeari"
version = "0.1.0"
description = "FOSS crossposting software built on humane modular design."
authors = [
  {name = "Mikita Wiśniewski", email = "rudzik8@protonmail.com"},
]
maintainers = [
  {name = "Mikita Wiśniewski", email = "rudzik8@protonmail.com"},
]
license = "LGPL-3.0-or-later"
license-files = ["LICEN[CS]E*", "AUTHORS.md"]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "click>=8.3.1",
    "flit-core>=3.12.0",
    "httpx>=0.28.1",
    "mistletoe>=1.5.1",
    "oschmod>=0.3.12",
    "python-frontmatter>=1.1.0",
]

[tool.setuptools]
packages = ["pomeari"]
package-dir = {"" = "src"}

[project.scripts]
pomeari = "pomeari.cli:cli"

[project.entry-points."pomeari.platforms"]
emptyshort = "pomeari.platforms.emptyshort.platform:EmptyShortPlatform"
longblank = "pomeari.platforms.longblank.platform:LongBlankPlatform"
mastodon = "pomeari.platforms.mastodon.platform:MastodonPlatform"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
